### PR TITLE
Skip deleting messages on insufficient permissions

### PR DESCRIPTION
**Pull request by peesock**
Adapted from https://github.com/victornpb/undiscord/issues/637

### CODE REVIEW

**Comment by bekkibau** [comment]
Thanks! Reproduced it by manually setting another user's id in `author` field on a channel.  

Before I merge, I just want to understand what steps you took to reproduce the issue as I tried to follow the steps in the original issue, but was unable to reproduce it. I suspect this might just be a workaround, but doesn't address the actual bug -- I'm suspecting a bug in the `Get Author` function causing it to grab the bot's id instead of the users. Any additional info would be appreciated!

 image

**Comment by peesock** [comment]
Yes, this is only a workaround; it shouldn't find messages from different owners, bot or not. I only found this bug on a specific private server bot, and only through an interaction (slash command) where the bot would send a message, replying with a special format `peesock used Add to gallery` or something like that. I tried with similar interactions like with Viggle and other servers' bots like starboard, but no error.

**Comment by peesock** [comment]
After diffing the json messages of the problematic bot vs the others, i see the only real differences are that it's missing the `interactionData`, `interactionMetadata`, and `nonce` objects, if that's useful.

**Comment by bekkibau** [comment]
Thanks for investigating the issue and providing some leads - I've added an issue with the details you provided. Sounds like the workaround is sufficient for now, so just documenting your findings in case we need a proper bug fix in the future.

**Pull request merged**
